version: '2'

services:
  backend:
    env_file:
        "./be_server/.env"
    build:
      context: ./be_server
      dockerfile: ./Dockerfile
    image: "vysakhvnair/erms-server"
    ports:
      - "3010:3010"
  frontend:
    env_file:
        "./fe_client/.env"
    build:
      context: ./fe_client
      dockerfile: ./Dockerfile
    image: "vysakhvnair/erms-client"
    ports:
      - "3005:3005"